# yaml-language-server: $schema=https://www.schemastore.org/github-issue-config.json
blank_issues_enabled: false
contact_links:
  - name: "✨ Feature Request"
    url: https://github.com/artivilla/outpaint/discussions/new/choose
    about: To request a feature, open a new Discussion or upvote an existing one if its already been requested
